server:
  port: 3333
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /

spring:
  application:
    name: api-getway
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone:  http://LAPTOP-BPGF8R1O:8762/eureka/,http://LAPTOP-BPGF8R1O:8761/eureka/
zuul:
  routes:
      hello-url:
            path: /hello/**
            serviceId: springbootservice
