server:
  servlet:
    context-path: /
  port: 8081
logging:
  config: classpath:Config/log4j2.yml
#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/Mappers/*Mapper.xml
  typeAliasesPackage: com.zzt.basic.model
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义SQL注入器
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false


spring:
  application:
    name: springbootservice
    profiles:
      active: test # 开发环境
  #####################################################################################################
  datasource:
    #    driver-class-name: com.mysql.jdbc.Driver
    #    url: jdbc:mysql://192.168.118.134:3306/uu_core
    #    username: root
    #    password: 123456
    #  阿里数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat,wall,logging
      # logging 是打印日志的配置名
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://192.168.118.134:3306/uu_core?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      username: root #用户名
      password: 123456 #密码
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      #filters: stat,wall,log4j
      #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true


  ########################################################################################
  data:
    mongodb: #mongoDB
      uri: mongodb://192.168.118.134:27017/data
  ####################################################################
  redis:
    database: 0   # Redis数据库索引（默认为0）
    host: 192.168.118.134 # Redis服务器地址
    #    host: 192.168.118.131 # Redis服务器地址
    port: 6379  # Redis服务器连接端口
    #    password: 123456
    #url:  # Connection URL, will override host, port and password (user will be ignored), e.g. redis://user:password@example.com:6379
    #    jedis:
    #      pool:
    #        max-active: 8 # 连接池最大连接数
    #         max-wait: 0 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    #        min-idle: 100 # 连接池中的最小空闲连接
    #        max-idle: 10 # 连接池中的最大空闲连接
    #        max-wait: # 连接超时时间（毫秒）
    #    cluster:
    #      nodes: 192.168.118.131:6382
    #######################################################################################
    #thymeleaf
    thymeleaf:
      encoding: UTF-8
      suffix: .html
      prefix: classpath:/
      enabled: true
      mode: HTML
      servlet:
        content-type: text/html
      cache: false
##########################################################################################
# spring security 安全框架
#  security:
#    user:
#      name: admin
#      password: admin


########################################################################################
eureka:
  client:
    service-url:
      defaultZone: http://192.168.2.169:8761/eureka/,http://192.168.2.169:8762/eureka/